CREATE TYPE indi_func AS ENUM ('Confirm', 'Confirm2', 'Confirm3', 'Baseline', 'Volume', 'Continue', 'Exit');

CREATE TABLE indicators (
       indicator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       parent_id INTEGER REFERENCES indicators(indicator_id) ON UPDATE CASCADE ON DELETE SET NULL,
       indicator VARCHAR(100) NOT NULL, -- name
       shift SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE indicator_default_func (
       indicator_id INTEGER PRIMARY KEY REFERENCES indicators(indicator_id) ON UPDATE CASCADE ON DELETE CASCADE,
       func indi_func NOT NULL
);

CREATE INDEX parents_index ON indicators(parent_id);
CREATE INDEX indi_names_index ON indicators(indicator);

CREATE TABLE indicator_inputs (
       -- id SERIAL PRIMARY KEY,
       indicator_id INTEGER REFERENCES indicators(indicator_id) ON UPDATE CASCADE ON DELETE CASCADE,
       index SMALLINT NOT NULL CHECK(index >= 0),
       input NUMERIC(12,4),   -- float is not reliable for comparing and restoring values and
       start NUMERIC(12,4),
       stop NUMERIC(12,4),
       step NUMERIC(12,4),
       CONSTRAINT input_notnull CHECK (
       (( input IS NOT NULL OR
         NOT ( start IS NULL OR stop IS NULL or step IS NULL ))
       ) -- either input needs to be set or all of start,stop,step
       ),
       CONSTRAINT indi_index_pk PRIMARY KEY (indicator_id, index)
);
